# -*- coding: utf-8 -*-
"""Drone_Tracking_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfkWCo6uxNf7tqEruMDjOCuQLZErRItD

#  Drone-Based Real-Time Vehicle Detection, Tracking, and Counting System using YOLOv8 and Deep SORT
###
"""

!pip install ultralytics
!pip install deep-sort-realtime

import cv2
import time
import torch
import numpy as np
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
from google.colab.patches import cv2_imshow


VIDEO_PATH      = "/content/video footage.mp4"
OUTPUT_PATH     = "output_v3.mp4"

YOLO_CONF       = 0.40
YOLO_IOU        = 0.40   # ← lowered: reduces duplicate boxes on large vehicles
YOLO_IMGSZ      = 1280   # ← increased: better detail on large/far vehicles

# COCO: 2=car, 3=motorcycle, 5=bus, 7=truck
VEHICLE_CLASSES = [2, 3, 5, 7]

# DeepSORT
MAX_AGE         = 40
N_INIT          = 2
MAX_IOU_DIST    = 0.60   # ← stricter: prevents merging two nearby vehicles


MAX_BOX_AREA_FRACTION = 0.12

# FIX B — Fragment merge: merge overlapping/close boxes that are the same vehicle
# (e.g. YOLO splits a truck into cab + trailer)
FRAGMENT_IOU_THRESH = 0.15   # if two boxes overlap >15%, merge them

LINE_Y_FRACTION = 0.55
BAND            = 12   # pixel band around counting line



def box_iou(b1, b2):
    """IoU between two [x,y,w,h] boxes."""
    ax1, ay1 = b1[0], b1[1]
    ax2, ay2 = b1[0]+b1[2], b1[1]+b1[3]
    bx1, by1 = b2[0], b2[1]
    bx2, by2 = b2[0]+b2[2], b2[1]+b2[3]
    ix = max(0, min(ax2,bx2) - max(ax1,bx1))
    iy = max(0, min(ay2,by2) - max(ay1,by1))
    inter = ix * iy
    union = b1[2]*b1[3] + b2[2]*b2[3] - inter
    return inter / union if union > 0 else 0

def merge_fragments(detections, iou_thresh):
    """
    Merge detections of the same class that heavily overlap (truck cab + trailer).
    Returns a reduced list where merged boxes become one large bounding box.
    """
    if len(detections) == 0:
        return detections

    used   = [False] * len(detections)
    merged = []

    for i, (box_i, conf_i, cls_i) in enumerate(detections):
        if used[i]:
            continue
        group_boxes = [box_i]
        group_conf  = [conf_i]
        used[i] = True

        for j, (box_j, conf_j, cls_j) in enumerate(detections):
            if used[j] or cls_j != cls_i:
                continue
            if box_iou(box_i, box_j) > iou_thresh:
                group_boxes.append(box_j)
                group_conf.append(conf_j)
                used[j] = True

        # Union bounding box of the group
        xs = [b[0] for b in group_boxes]
        ys = [b[1] for b in group_boxes]
        x2s = [b[0]+b[2] for b in group_boxes]
        y2s = [b[1]+b[3] for b in group_boxes]
        mx, my = min(xs), min(ys)
        mw, mh = max(x2s)-mx, max(y2s)-my
        merged.append(([mx, my, mw, mh], max(group_conf), cls_i))

    return merged


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Use yolov8s (small) — meaningfully better than yolov8n on trucks/buses
model = YOLO("yolov8s.pt")
model.to(device)
print("Model loaded.")

# Tracker created ONCE outside the loop
tracker = DeepSort(
    max_age=MAX_AGE,
    n_init=N_INIT,
    max_iou_distance=MAX_IOU_DIST,
    embedder="mobilenet",
    half=True,
    embedder_gpu=(device == "cuda"),
)

cap = cv2.VideoCapture(VIDEO_PATH)
assert cap.isOpened(), f"Cannot open: {VIDEO_PATH}"

width        = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height       = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps          = cap.get(cv2.CAP_PROP_FPS) or 25.0
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
frame_area   = width * height
line_y       = int(height * LINE_Y_FRACTION)

print(f"Video: {width}x{height} @ {fps:.1f}fps  ({total_frames} frames)")

out = cv2.VideoWriter(OUTPUT_PATH, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))

counted_ids   = set()
vehicle_count = 0
frame_idx     = 0


while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_idx += 1
    t0 = time.time()

    # ── 1. DETECT ─────────────────────────────────
    results = model(frame, conf=YOLO_CONF, iou=YOLO_IOU,
                    imgsz=YOLO_IMGSZ, verbose=False)[0]

    raw_dets = []
    for box in results.boxes.data:
        x1, y1, x2, y2, conf, cls = box.tolist()
        cls = int(cls)
        if cls not in VEHICLE_CLASSES:
            continue

        bw, bh = int(x2-x1), int(y2-y1)

        # FIX A — Drop ghost / oversized boxes
        if (bw * bh) > (frame_area * MAX_BOX_AREA_FRACTION):
            continue

        raw_dets.append(([int(x1), int(y1), bw, bh], float(conf), cls))

    # FIX B — Merge fragmented truck/bus detections
    detections = merge_fragments(raw_dets, FRAGMENT_IOU_THRESH)

    # ── 2. TRACK ──────────────────────────────────
    tracks = tracker.update_tracks(detections, frame=frame)

    # ── 3. DRAW ───────────────────────────────────
    cv2.line(frame, (0, line_y), (width, line_y), (0, 0, 255), 2)
    cv2.putText(frame, "COUNTING LINE", (10, line_y - 8),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1)

    for track in tracks:
        if not track.is_confirmed():
            continue

        l, t, r, b  = map(int, track.to_ltrb())
        track_id    = track.track_id
        cx, cy      = (l+r)//2, (t+b)//2
        box_area    = (r-l) * (b-t)

        # Skip if tracker produces an oversized box (lingering ghost)
        if box_area > frame_area * MAX_BOX_AREA_FRACTION:
            continue

        # Count crossing
        if abs(cy - line_y) < BAND and track_id not in counted_ids:
            counted_ids.add(track_id)
            vehicle_count += 1

        cv2.rectangle(frame, (l, t), (r, b), (0, 255, 0), 2)
        cv2.circle(frame,    (cx, cy), 4, (0, 255, 255), -1)
        cv2.putText(frame, f"ID:{track_id}", (l, t-8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 255), 1)

    # ── 4. HUD ────────────────────────────────────
    fps_disp     = 1.0 / max(time.time()-t0, 1e-6)
    active       = sum(1 for t in tracks if t.is_confirmed())
    cv2.rectangle(frame, (10,5), (260,100), (0,0,0), -1)
    cv2.putText(frame, f"Vehicles Counted: {vehicle_count}",
                (15,35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,0,255), 2)
    cv2.putText(frame, f"Active Tracks:    {active}",
                (15,65), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255,255,255), 1)
    cv2.putText(frame, f"FPS: {int(fps_disp)}",
                (15,90), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,255,0), 1)

    out.write(frame)

    if frame_idx % 100 == 0:
        pct = frame_idx / total_frames * 100 if total_frames else 0
        print(f"  Frame {frame_idx}/{total_frames} ({pct:.0f}%) — Counted: {vehicle_count}")

cap.release()
out.release()
cv2.destroyAllWindows()
print(f"\n✅ Done! Total vehicles: {vehicle_count}")
print(f"Saved to: {OUTPUT_PATH}")

# Preview a frame from the output
import cv2
from google.colab.patches import cv2_imshow
cap2 = cv2.VideoCapture(OUTPUT_PATH)
total = int(cap2.get(cv2.CAP_PROP_FRAME_COUNT))
cap2.set(cv2.CAP_PROP_POS_FRAMES, int(total * 0.4))
ret, preview = cap2.read()
cap2.release()
if ret:
    cv2_imshow(preview)

from google.colab import files
files.download(OUTPUT_PATH)